In [3]:
import numpy as np

# CREAR UN ARRAY 1D
z = np.array([1 , 2 , 3])

print(z)


[1 2 3]


In [4]:
# Crear un array 2D
array2D = np.array([ [1 , 2 , 3 ] , [4,5,6]])
print(array2D)

[[1 2 3]
 [4 5 6]]


In [5]:
# genera un array de rango de numeros

a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [6]:
# CREAR UN ARRAY DE CEROS
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [7]:
# CREAR UN ARRAY DE UNOS
unos = np.ones(5)
print(unos)

[1. 1. 1. 1. 1.]


In [8]:
# DIVIDIR UNIFORMEMENTE UN ARRAY
division = np.linspace( 0. , 1 , 10 )
print(division)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [9]:
# ARREGLO DE IDENTIDAD
identidad = np.eye(10)
print(identidad)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
# CREAR NUMEROS ALEATORIOS EN PYTHON
rands = np.random.rand(10)
print(rands)

[0.29019337 0.88775311 0.60764103 0.91992001 0.36576686 0.8123494
 0.37042947 0.17793958 0.85641645 0.46992375]


In [11]:
# TRANSFORMA EL ARREGLO EN FORMA DIFERENTE
#2x3
arreglo = np.array(np.arange(0 , 6))
print(arreglo.shape)
arreglo = arreglo.reshape(3,2)
# devuelve la forma
print(arreglo.shape)
print(arreglo)

(6,)
(3, 2)
[[0 1]
 [2 3]
 [4 5]]


In [12]:
# ENCONTRAR EL VALOR MAXIMO DEL ARRAY
maximo = arreglo.max()
print(maximo)

5


In [14]:
# ENCONTRAR EL INDICE DEL MINIMO VALOR DEL ARRAY
min = arreglo.argmin()
print(min)

0
